### ISSUE TITLE
Dds file

### ISSUE THREAD

**Issue by Padre19** [HungryForFood/Enlightenment-Era-Vox-Populi-#1]
EnlightenmentVP_Buildings_45.dds is broken.

**Comment by HungryForFood** [comment]
How broken, do you have a screenshot?

**Comment by Padre19** [comment]
The icons of the two buildings are missing in the tech tree.

**Comment by HungryForFood** [comment]
I see it now.

**Comment by HungryForFood** [comment]
Ok done. I'm force pushing btw, in case you are using git.

**Comment by Padre19** [comment]
Thank you!
